@startuml
interface IEnemy {
    IsTouchingPlayer : bool <<get>>
    SetIsTouchingPlayer(isTouchingPlayer:bool) : void
    DestroySelf() : void
}
class "List`1"<T> {
}
IEnemy --> "MainCamera" Camera
IEnemy --> "Position" Vector3
IEnemy --> "Rigidbody" Rigidbody
IEnemy --> "CloseEnemies<GameObject>" "List`1"
IEnemy --> "HitPoint" HitPoint
IEnemy --> "MovementParameter" MovementParameter
IEnemy --> "SpawnPositionInScreen" Vector3
IEnemy --> "SpawnPositionInWorld" Vector3
IEnemy --> "PlayerInstance" GameObject
IEnemy --> "EventManager" EventManager
@enduml
