@startuml
class EnemyScriptableObject {
    - enemyName : string
    + EnemyName : string <<get>>
    - description : string
    + Description : string <<get>>
    - evaluation : int
    + Evaluation : int <<get>>
    - maxHitPoint : int
    + MaxHitPoint : int <<get>>
    - attackPower : int
    + AttackPower : int <<get>>
    - movingSpeed : int
    + MovingSpeed : int <<get>>
    - chasingAccuracy : float
    + ChasingAccuracy : float <<get>>
    + CheckStateTransitions() : State.IState.State
    + InitializeController(enemy:IEnemy) : State.IState.State
}
EnemyScriptableObject --> "enemyPrefab" GameObject
EnemyScriptableObject --> "EnemyPrefab" GameObject
EnemyScriptableObject --> "controller" IController
@enduml
