@startuml
class WaveScriptableObject {
    - enemyNumberInGroup : int
    + EnemyNumberInGroup : int <<get>>
    - groupNumber : int
    + GroupNumber : int <<get>>
    - minElementNumberInGroup : int
    + MinElementNumberInGroup : int <<get>>
    + HasStrongEnemy : bool <<get>> <<set>>
    + {static} SetFormationEvaluation(formationType:FormationType) : int
    + SetStrongEnemyEvaluation() : int
}
enum FormationType {
    OneDirection,
    OneDirectionTwoLines,
    TwoDirection,
    ThreeDirection,
    EveryDirection,
}
WaveScriptableObject --> "enemyScriptableObject" EnemyScriptableObject
WaveScriptableObject --> "EnemyScriptableObject" EnemyScriptableObject
WaveScriptableObject --> "strongEnemyScriptableObject" EnemyScriptableObject
WaveScriptableObject --> "StrongEnemyScriptableObject" EnemyScriptableObject
WaveScriptableObject --> "formationType" FormationType
WaveScriptableObject --> "FormationType" FormationType
@enduml
