@startuml
class StraightLinerController {
    + <<override>> CheckTransitions() : IState.State
    # <<override>> AddUniqueStates() : void
    # <<override>> SetInitialState() : IState.State
}
BaseController <|-- StraightLinerController
@enduml
