@startuml
class GoStraightState {
    + GoStraightState(enemy:IEnemy)
    - _disappearTimer : float
    # <<override>> OnEntry() : void
    # <<override>> OnUpdate() : void
    # <<override>> OnFixedUpdate() : void
    # <<override>> OnExit() : void
    - GetTargetPositionInScreen(spawnPositionInViewport:Vector3) : Vector3
    + IsOutOfScreen() : bool
}
BaseState <|-- GoStraightState
IIsOutOfScreen <|-- GoStraightState
GoStraightState --> "State" State
GoStraightState --> "rayCasterFromScreen" RayCasterFromScreen
@enduml
