@startuml
class EnemySpawner {
    - _isPeriodEnd : bool
    + StageLevel : int <<get>>
    - Awake() : void
    - Start() : void
    - FixedUpdate() : void
    + IncreaseStageLevel() : void
    - <<async>> SpawnEnemyInPeriod(cancellationToken:CancellationToken, stageScriptableObject:StageScriptableObject) : UniTaskVoid
    + CancelSpawnEnemyInPeriod() : void
    - {static} SetWaveScriptableObjectsInPeriod(stageScriptableObject:StageScriptableObject) : List<WaveScriptableObject>
    - SpawnEnemy(waveScriptableObject:WaveScriptableObject) : void
    - GetSpawnPositionInScreen(enemyNumberInGroup:int, groupNumber:int, minElementNumber:int, directionNumber:int, isTwoLines:bool) : List<Vector3>
}
class "Subject`1"<T> {
}
class "IObservable`1"<T> {
}
MonoBehaviour <|-- EnemySpawner
EnemySpawner --> "_container" DiContainer
EnemySpawner --> "_getSpawnPoints" GetSpawnPoints
EnemySpawner --> "_rayCasterFromScreen" RayCasterFromScreen
EnemySpawner --> "_cts" CancellationTokenSource
EnemySpawner o-> "_onPeriodEnd<Unit>" "Subject`1"
EnemySpawner --> "OnPeriodEnd<Unit>" "IObservable`1"
@enduml
